"""
Fix Suggestion API
==================
Provides on-demand, language-specific secure code fix suggestions
for a specific finding within a completed scan.

Endpoints:
  GET  /api/fix/{scan_id}/{finding_index}
       Returns a structured fix with before/after code, explanation,
       and testing guidance — powered by FixSuggestionChain (RAG + Groq).

Authentication: X-API-Key header (via require_api_key dependency in main.py)
"""

import difflib
import base64
import logging
import os
import re
from urllib.parse import urlparse
from typing import Any, Dict, Optional

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from backend.storage.findings_repository import FindingsRepository

logger = logging.getLogger(__name__)

router = APIRouter()

class DirectFixRequest(BaseModel):
    language: Optional[str] = "python"
    path: Optional[str] = "app.py"
    vulnerable_code: str
    rule_id: Optional[str] = "security-finding"
    message: Optional[str] = "Potential security vulnerability"


class PullRequestFixRequest(BaseModel):
    repo_url: str
    file_path: str
    vulnerable_code: str
    secure_code: str
    base_branch: str = "main"
    title: str = "fix: remediate security finding"
    body: str = "Automated security fix generated by AI AppSec Platform."

def generate_unified_diff(vulnerable_code: str, secure_code: str, file_path: str = "vulnerable_file") -> str:
    if not vulnerable_code or not secure_code:
        return ""
    vuln_lines = [l + "\n" for l in vulnerable_code.splitlines()]
    secure_lines = [l + "\n" for l in secure_code.splitlines()]
    diff = difflib.unified_diff(
        vuln_lines,
        secure_lines,
        fromfile=f"a/{file_path}",
        tofile=f"b/{file_path}",
        lineterm="",
    )
    return "\n".join(diff)


def _github_repo_parts(repo_url: str) -> tuple[str, str]:
    parsed = urlparse(repo_url)
    if parsed.scheme != "https" or parsed.hostname != "github.com":
        raise HTTPException(status_code=400, detail="Only https://github.com repositories are supported")
    parts = [part for part in parsed.path.strip("/").split("/") if part]
    if len(parts) != 2 or not all(re.fullmatch(r"[A-Za-z0-9_.-]+", part) for part in parts):
        raise HTTPException(status_code=400, detail="repo_url must be https://github.com/<owner>/<repo>")
    return parts[0], parts[1].removesuffix(".git")


def _safe_relative_path(file_path: str) -> str:
    normalized = file_path.replace("\\", "/")
    if not normalized or normalized.startswith("/") or re.match(r"^[A-Za-z]:", normalized):
        raise HTTPException(status_code=400, detail="file_path must be relative")
    parts = normalized.split("/")
    if any(part in {"", ".", ".."} for part in parts):
        raise HTTPException(status_code=400, detail="file_path contains unsafe path segments")
    return "/".join(parts)


def _safe_branch_name(branch: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9._/-]{1,200}", branch) or branch.startswith(("/", "-")) or ".." in branch:
        raise HTTPException(status_code=400, detail="Invalid Git branch name")
    return branch


def create_github_pull_request(payload: PullRequestFixRequest, token: str, client: httpx.Client | None = None) -> dict:
    """Commit an exact source replacement to GitHub and open a pull request."""
    if not token:
        raise HTTPException(status_code=503, detail="GITHUB_TOKEN is not configured")
    owner, repo = _github_repo_parts(payload.repo_url)
    file_path = _safe_relative_path(payload.file_path)
    base_branch = _safe_branch_name(payload.base_branch)
    if not payload.vulnerable_code or not payload.secure_code:
        raise HTTPException(status_code=400, detail="Both vulnerable_code and secure_code are required")

    branch = f"appsec/fix-{os.urandom(5).hex()}"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    api = client or httpx.Client(base_url="https://api.github.com", headers=headers, timeout=20.0)
    close_client = client is None
    try:
        repo_response = api.get(f"/repos/{owner}/{repo}", headers=headers)
        if repo_response.status_code >= 300:
            raise HTTPException(status_code=502, detail="GitHub repository lookup failed")
        base_sha = repo_response.json().get("object", {}).get("sha")
        if not base_sha:
            ref_response = api.get(f"/repos/{owner}/{repo}/git/ref/heads/{base_branch}", headers=headers)
            if ref_response.status_code >= 300:
                raise HTTPException(status_code=502, detail="Could not resolve base branch")
            base_sha = ref_response.json()["object"]["sha"]

        content_response = api.get(
            f"/repos/{owner}/{repo}/contents/{file_path}",
            params={"ref": base_branch},
            headers=headers,
        )
        if content_response.status_code >= 300:
            raise HTTPException(status_code=502, detail="Could not read target file from GitHub")
        content_data = content_response.json()
        original = base64.b64decode(content_data["content"]).decode("utf-8")
        occurrences = original.count(payload.vulnerable_code)
        if occurrences != 1:
            raise HTTPException(status_code=409, detail="Vulnerable code must occur exactly once in the target file")
        updated = original.replace(payload.vulnerable_code, payload.secure_code, 1)

        ref_response = api.post(
            f"/repos/{owner}/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch}", "sha": base_sha},
            headers=headers,
        )
        if ref_response.status_code >= 300:
            raise HTTPException(status_code=502, detail="Could not create fix branch")

        commit_response = api.put(
            f"/repos/{owner}/{repo}/contents/{file_path}",
            json={
                "message": payload.title,
                "content": base64.b64encode(updated.encode("utf-8")).decode("ascii"),
                "sha": content_data["sha"],
                "branch": branch,
            },
            headers=headers,
        )
        if commit_response.status_code >= 300:
            raise HTTPException(status_code=502, detail="Could not commit security fix")

        pr_response = api.post(
            f"/repos/{owner}/{repo}/pulls",
            json={"title": payload.title, "body": payload.body, "head": branch, "base": base_branch},
            headers=headers,
        )
        if pr_response.status_code >= 300:
            raise HTTPException(status_code=502, detail="Could not create pull request")
        result = pr_response.json()
        return {"branch": branch, "file_path": file_path, "diff_patch": generate_unified_diff(payload.vulnerable_code, payload.secure_code, file_path), "pull_request": {"number": result.get("number"), "url": result.get("html_url"), "state": result.get("state")}}
    finally:
        if close_client:
            api.close()


@router.post("/pull-request", summary="Create a GitHub pull request with a security fix")
async def create_fix_pull_request(payload: PullRequestFixRequest) -> dict:
    token = os.getenv("GITHUB_TOKEN", "")
    return await __import__("asyncio").to_thread(create_github_pull_request, payload, token)

@router.post(
    "/generate",
    summary="Generate fix for custom finding payload",
    description="Generates secure remediation code and unified diff for raw finding input.",
)
async def generate_direct_fix(payload: DirectFixRequest) -> Dict[str, Any]:
    finding = {
        "finding": {
            "rule_id": payload.rule_id,
            "message": payload.message,
            "path": payload.path,
            "extra": {"lines": payload.vulnerable_code, "message": payload.message},
            "metadata": {"language": payload.language},
        }
    }
    
    if os.getenv("GROQ_API_KEY"):
        try:
            from backend.ai.chains.fix_suggestion_chain import FixSuggestionChain
            fix = FixSuggestionChain().generate_fix(finding)
        except Exception as exc:
            logger.warning("AI fix generation failed: %s; using fallback", exc)
            fix = _local_fix(finding)
    else:
        fix = _local_fix(finding)
        
    fix["diff_patch"] = generate_unified_diff(
        fix.get("vulnerable_code", payload.vulnerable_code),
        fix.get("secure_code", ""),
        payload.path or "source_file"
    )
    return {"fix": fix}

@router.get(
    "/{scan_id}/{finding_index}",
    summary="Generate secure fix for a finding",
    description=(
        "Retrieves the finding at *finding_index* from the scan result, "
        "then uses the RAG-augmented FixSuggestionChain to generate a "
        "language-specific secure code fix with before/after snippets."
    ),
)
async def get_fix_suggestion(
    scan_id: str,
    finding_index: int,
) -> Dict[str, Any]:
    # 1. Load scan from findings repository
    findings_repo = FindingsRepository()
    scan = findings_repo.get_scan(scan_id)

    if not scan:
        raise HTTPException(
            status_code=404,
            detail=f"Scan '{scan_id}' not found.",
        )

    results = scan.get("findings", [])
    if finding_index < 0 or finding_index >= len(results):
        raise HTTPException(
            status_code=404,
            detail=(
                f"Finding index {finding_index} out of range. "
                f"Scan has {len(results)} findings."
            ),
        )

    finding = results[finding_index]

    # 2. Extract the representative finding if deduplicated group format
    if "representative_finding" in finding:
        finding = finding["representative_finding"]

    # 3. Generate a local fallback unless the optional AI provider is ready.
    try:
        if not os.getenv("GROQ_API_KEY"):
            fix = _local_fix(finding)
        else:
            try:
                from backend.ai.chains.fix_suggestion_chain import FixSuggestionChain

                fix = FixSuggestionChain().generate_fix(finding)
            except Exception as exc:
                logger.warning("AI fix unavailable; returning local guidance: %s", exc)
                fix = _local_fix(finding)
                
        vuln_code = fix.get("vulnerable_code", "")
        sec_code = fix.get("secure_code", "")
        filePath = finding.get("finding", {}).get("path", "file")
        fix["diff_patch"] = generate_unified_diff(vuln_code, sec_code, filePath)

        return {
            "scan_id": scan_id,
            "finding_index": finding_index,
            "fix": fix,
        }
    except Exception as exc:
        logger.error("FixSuggestionChain failed for scan=%s index=%d: %s",
                     scan_id, finding_index, exc)
        raise HTTPException(
            status_code=500,
            detail=f"Fix generation failed: {exc}",
        )


def _local_fix(finding: dict) -> Dict[str, Any]:
    """Return useful deterministic guidance when AI is not configured."""
    raw = finding.get("finding", finding)
    vulnerable_code = raw.get("extra", {}).get("lines") or raw.get("snippet", {}).get("vulnerable_line", "")
    secure_code = f"# Secure Fix:\n# {raw.get('extra', {}).get('message', 'Apply parameterized input validation')}"
    
    return {
        "language": raw.get("metadata", {}).get("language", "unknown"),
        "vulnerable_code": vulnerable_code,
        "secure_code": secure_code,
        "explanation": raw.get("extra", {}).get("message", "Review and remediate this finding."),
        "security_libraries": [],
        "additional_hardening": [
            "Use parameterized input queries and sanitize untrusted input.",
            "Enforce strict input length and type validation."
        ],
        "testing_guidance": "Re-run the static analysis scan and add a unit test for vulnerable inputs.",
        "ai_unavailable": True,
    }

